#! /bin/sh
setxkbmap latam &

pgrep -x sxhkd > /dev/null || sxhkd &

# escritorios solo en la laptop (10 iconos)
bspc monitor eDP -d "" "" "" "" "" "" "" "" "" ""

# monitor externo: un unico escritorio (si esta conectado)
if bspc query -M --names | grep -q '^HDMI-A-0$'; then
	bspc monitor HDMI-A-0 -d ""
fi

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color "#D70A53"
bspc config normal_border_color "#2b2b2e"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
polybar main &
feh --bg-scale ~/.dotfiles/wallpapers/fondo.png &
picom &
dunst &
bspc rule -a flameshot state=floating
bspc rule -a thunar state=floating rectangle=1000x650+0+0 center=true
bspc rule -a calendario state=floating rectangle=700x560+0+0 center=true
