; ═══════════════════════════════════════════════
;  polybar — Rice "Debian Crimson" v2
;  Iconos con escapes unicode (guia 5.3)
; ═══════════════════════════════════════════════

[bar/main]
width = 100%
height = 28
background = #ee0f0f12
foreground = #b3b3b8
padding-left = 1
padding-right = 1
module-margin = 1
font-0 = JetBrainsMono Nerd Font Mono:size=11;2
modules-left = logo bspwm
modules-center = date
modules-right = network cpu memory battery volume mic power

[module/logo]
type = custom/text
label = ""
label-foreground = #E8B04B
label-padding = 1

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
; click en un escritorio = saltar a el
label-focused = %{A1:bspc desktop -f ^%index%:}%name%%{A}
label-focused-background = #D70A53
label-focused-foreground = #0f0f12
label-focused-padding = 2
label-occupied = %{A1:bspc desktop -f ^%index%:}%name%%{A}
label-occupied-foreground = #D70A53
label-occupied-padding = 2
label-empty = %name%
label-empty-foreground = #45474e
label-empty-padding = 2
label-urgent = %name%
label-urgent-background = #E8B04B
label-urgent-foreground = #0f0f12
label-urgent-padding = 2
scroll-up = bspc desktop -f prev.local
scroll-down = bspc desktop -f next.local

[module/date]
type = internal/date
interval = 5
date = %a %d
time = %H:%M
label = "%{F#E8B04B}%{F-} %date% · %time%"
; click en la fecha -> calendario flotante de 3 meses
click-left = kitty --class calendario --name calendario -e sh -c 'cal -3; echo; printf "Enter para cerrar: "; read x'

[module/network]
type = custom/script
exec = ~/.local/bin/red-wifi.sh
interval = 3
click-left = ~/.local/bin/red-wifi.sh toggle

[module/cpu]
type = internal/cpu
interval = 2
label = "%{F#D70A53}%{F-} %percentage%%"

[module/memory]
type = internal/memory
interval = 2
label = "%{F#E8B04B}%{F-} %percentage_used%%"

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP0
full-at = 98
low-at = 20
poll-interval = 5
format-charging = <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-low = <label-low>
format-full = <label-full>
label-charging = "%{F#E8B04B}%{F-} %percentage%%"
label-discharging = %percentage%%
label-low = " %percentage%%  LOW!"
label-full = "%{F#E8B04B}%{F-} full"
ramp-capacity-0 = "%{F#D70A53}%{F-}"
ramp-capacity-1 = "%{F#D70A53}%{F-}"
ramp-capacity-2 = "%{F#E8B04B}%{F-}"
ramp-capacity-3 = "%{F#E8B04B}%{F-}"
ramp-capacity-4 = "%{F#E8B04B}%{F-}"

[module/volume]
type = custom/script
exec = ~/.local/bin/estado-volumen.sh
interval = 2
click-left = pactl set-sink-mute @DEFAULT_SINK@ toggle
scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5%
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5%

[module/mic]
type = custom/script
exec = ~/.local/bin/estado-microfono.sh
interval = 3
click-left = pactl set-source-mute @DEFAULT_SOURCE@ toggle

[module/power]
type = custom/text
label = ""
label-foreground = #D70A53
label-padding = 1
click-left = ~/.local/bin/powermenu.sh
