# ============================================================
#  picom — Rice "Debian Crimson" (variante VM)
#  Sin glx/blur: en maquinas virtuales da glitches.
#  Systray con fondo real (sin sombras) para no romper.
# ============================================================

backend = "xrender";
vsync = false;

corner-radius = 10;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "window_type = 'dock'"
];

shadow = false;
fading = false;

opacity-rule = [
  "92:class_g = 'kitty'",
  "95:class_g = 'Thunar'"
];
